POST  https://localhost:7172/auth/register
Content-Type: application/json

{
    "firstname":"",
    "lastname":"",
    "email":"add@S",
    "password":"dds"
}

###

POST https://localhost:7172/auth/login
Content-Type: application/json

{
    "email":"ss",
    "password":"dds"
}


