POST  https://localhost:7172/auth/register
Content-Type: application/json

{
    "firstname":"s",
    "lastname":"s",
    "email":"a@S",
    "password":"s"
}

###

POST https://localhost:7172/auth/login
Content-Type: application/json

{
    "email":"a@S",
    "password":"s"
}


